#!/bin/bash
#BSUB -J realignBAM
#BSUB -n 1
#BSUB -R span[hosts=1]
#BSUB -R rusage[mem=15]
#BSUB -W 07:00
#BSUB -o %J.stdout
#BSUB -e %J.stderr

/lila/data/kentsis/testfiles/K052M2_test/.conda/pkgs/bwa-0.7.17-ha92aebf_3/bin/bwa index -p resources_broad_hg38_v0_Homo_sapiens_assembly38.fasta -a bwtsw /lila/data/kentsis/testfiles/m2_test/m2/resources_broad_hg38_v0_Homo_sapiens_assembly38.fasta