#!/bin/bash
#BSUB -J realignBAM
#BSUB -n 1
#BSUB -R span[hosts=1]
#BSUB -R rusage[mem=15]
#BSUB -W 05:00
#BSUB -o %J.stdout
#BSUB -e %J.stderr

java -jar /lila/data/kentsis/testfiles/K052M2_test/picard.jar RevertSam I=/lila/data/kentsis/testfiles/K052M2_test/K052_DNA_subset_remove_unaligned.bam O=/lila/data/kentsis/testfiles/K052M2_test/K052_DNA_subset_unaligned.bam

java -jar /lila/data/kentsis/testfiles/K052M2_test/picard.jar SamToFastq I=/lila/data/kentsis/testfiles/K052M2_test/K052_DNA_subset_unaligned.bam FASTQ=/lila/data/kentsis/testfiles/K052M2_test/K052_DNA_subset_r1.fastq SECOND_END_FASTQ=/lila/data/kentsis/testfiles/K052M2_test/K052_DNA_subset_r2.fastq
